services:
  db:
    image: postgres:17
    container_name: database
    environment:
      - POSTGRES_USER=princesas
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tp_princesas
    ports:
      - 5432:5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data