name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto a tu rama principal

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frontend/index.html  # Directorio raíz de tu proyecto
